Document that sequence dictionary converts are computationally expensive, and add a cache
fulcrumgenomics/fgbio pull request #644
Opened 2021-01-04 23:40 UTC by nh13

CC: @mjhipp https://github.com/fulcrumgenomics/fgbio/issues/579#issuecomment-754228920

This PR has two commits for consideration:
1. document that repeatedly converting sequence dictionaries using the provided implicits is expensive
2. add a cache so that "it just works" for anybody using the implicits.  This is so that anybody that converts over to the new `SequenceDictionary` class and friends don't experience the same pain as @mjhipp 

100 iterations on hs38DH

```
[2021/01/04 15:40:10 | FgBioMain | Info] Executing DictLoop from fgbio version 1.4.0-22b0efc-SNAPSHOT as nhomer@nils-fg.local on JRE 1.8.0_212-b10 with snappy, JdkInflater, and JdkDeflater
[2021/01/04 15:40:11 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:40:11 | DictLoop | Info] Accessing SAMSequenceDictionary 100 times WITHOUT conversion step.
[2021/01/04 15:40:11 | DictLoop | Info] Elapsed time: 1.690521 ms.
[2021/01/04 15:40:11 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:40:11 | DictLoop | Info] Accessing fasta.SequenceDictionary 100 times WITHOUT conversion step.
[2021/01/04 15:40:11 | DictLoop | Info] Elapsed time: 0.413097 ms.
[2021/01/04 15:40:11 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:40:11 | DictLoop | Info] Accessing SAMSequenceDictionary 100 times with asSam conversion step.
[2021/01/04 15:40:11 | DictLoop | Info] Elapsed time: 39.607902 ms.
[2021/01/04 15:40:11 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:40:11 | DictLoop | Info] Accessing fasta.SequenceDictionary 100 times with fromSam conversion step.
[2021/01/04 15:40:11 | DictLoop | Info] Elapsed time: 12.715213 ms.
[2021/01/04 15:40:11 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:40:11 | FgBioMain | Info] DictLoop completed. Elapsed time: 0.03 minutes.
```

100,000 iterations on hs38DH:

```
[2021/01/04 15:37:14 | FgBioMain | Info] Executing DictLoop from fgbio version 1.4.0-22b0efc-SNAPSHOT as nhomer@nils-fg.local on JRE 1.8.0_212-b10 with snappy, JdkInflater, and JdkDeflater
[2021/01/04 15:37:14 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:37:14 | DictLoop | Info] Accessing SAMSequenceDictionary 100000 times WITHOUT conversion step.
[2021/01/04 15:37:14 | DictLoop | Info] Elapsed time: 5.879807 ms.
[2021/01/04 15:37:14 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:37:14 | DictLoop | Info] Accessing fasta.SequenceDictionary 100000 times WITHOUT conversion step.
[2021/01/04 15:37:14 | DictLoop | Info] Elapsed time: 3.194493 ms.
[2021/01/04 15:37:14 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:37:14 | DictLoop | Info] Accessing SAMSequenceDictionary 100000 times with asSam conversion step.
[2021/01/04 15:37:14 | DictLoop | Info] Elapsed time: 44.157055 ms.
[2021/01/04 15:37:14 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:37:14 | DictLoop | Info] Accessing fasta.SequenceDictionary 100000 times with fromSam conversion step.
[2021/01/04 15:37:16 | DictLoop | Info] Elapsed time: 1841.079818 ms.
[2021/01/04 15:37:16 | DictLoop | Info] -----------------------------------------------------------------------------
[2021/01/04 15:37:16 | FgBioMain | Info] DictLoop completed. Elapsed time: 0.06 minutes.
```

2021-01-04 23:41 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/fasta/SequenceDictionary.scala
> +        val locus = FgBioDef.GenomicRange(range) match {
This is unrelated

2021-01-04 23:42 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/fasta/SequenceDictionary.scala
> +  override lazy val hashCode: Int = {
caching the hashcode is a big win

2021-01-05 18:33 UTC, mjhipp commented
This is great. Thanks @nh13!

2021-02-24 00:37 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/fasta/SequenceDictionary.scala
> +  var EnableCache: Boolean = true
I'd be open to making this `false` by default

2021-02-26 18:37 UTC, tfenne requested changes
I think the caching here is really problematic on a couple of fronts.

1. Synchronization - the caches are all mutable HashMaps which are not internally synchronized, and they is no protection stopping them from being written to from multiple threads simultaneously (nor read simultaneously with writes).  So if e.g. someone were to do something (like read multiple BAMs) on multiple threads and cause conversions to take place they could well experience exceptions due to concurrent updates of the cache.

2. It's basically a memory leak.  If I have a large sequence dictionary that I use briefly, or many sequence dictionaries that I use briefly, this cache will cause them all to be retained in memory and that's quite counter-intuitive.  My best suggestion for this would be to use a `WeakHashMap` instead which will allow the GC to remove things from the cache when they are not referenced/held elsewhere.  The downside of that though is that the it uses weak references on the keys, and so if you read 1 BAM and populate the cache, then let go of that BAM's header, the GC is free to reclaim those entries from cache, even if another BAM header with the logically same sequence dictionary is in memory.  I think the ideal thing here would be have a `SoftHashMap` that leverages `SoftReference`s which are somewhat similar to `WeakReferences` but have semantics that better match our need - specifically `WeakReferences` are always cleared once there are only `WeakReferences` to an object (i.e. it's greedy) whereas `SoftReferences` are only cleared when a) there are only `SoftReferences` to an object _and_ the GC needs to reclaim that memory to avoid an out of memory error.

2022-02-28 22:06 UTC, closed without merging