GroupReadsByUmi does not require single contig
fulcrumgenomics/fgbio pull request #648
Opened 2021-01-28 01:21 UTC by mjhipp

In order for pairs from different chromosomes to be grouped together, `ReadInfo` was changed to prioritize the chromosome, and take the lower chromosome of the two reads.

2021-02-04 18:16 UTC, mjhipp commented
@nh13 would you rather me make this change optional/experimental?

2021-02-04 18:22 UTC, nh13 commented
I think an opt-in model would be great, `--allow-inter-contig-grouping` or some better name than that, but the rest looks great to me!

2021-02-04 19:47 UTC, mjhipp commented
Thanks @nh13! Updated to make the feature opt-in.

2021-02-04 19:47 UTC, nh13 approved these changes

2021-02-24 00:33 UTC, nh13 requested changes
I think there's one place where the `contig` or `refIndex` wasn't considered, but should be.  If you agree, the rest looks good to me.

2021-02-24 00:33 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/umi/GroupReadsByUmi.scala
> +        val result = if (chrom < mateChrom || chrom == mateChrom && (recPos < matePos || (recPos == matePos && !recNeg))) {
Just adding one extra bracket to make 100% clear the precedence of `||` and `&&`:
```suggestion
        val result = if (chrom < mateChrom || (chrom == mateChrom && (recPos < matePos || (recPos == matePos && !recNeg)))) {
```

2021-02-24 00:33 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/umi/GroupReadsByUmi.scala
>          val r1Lower = pos1 < pos2 || pos1 == pos2 && r1.positiveStrand
I think you want to now incorporate contig coordinates here.
```suggestion
        val r1Lower = r1.refIndex < r2.refIndex || (r1.refIndex == r2.refIndex && (pos1 < pos2 || (pos1 == pos2 && r1.positiveStrand)))
```

2021-02-24 00:33 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/umi/GroupReadsByUmi.scala
>          val r1Lower = pos1 < pos2 || pos1 == pos2 && r1.positiveStrand
Bonus points for a unit test that checks this.

2021-03-01 20:25 UTC, merged

2021-03-01 20:25 UTC, nh13 commented
Thank-you @mjhipp this is great!