[feature] add a cache into CorrectUmis
fulcrumgenomics/fgbio pull request #702
Opened 2021-09-08 22:44 UTC by nh13

This is useful when we have a large set (>1K) of Umis

2021-09-09 10:45 UTC, pamelarussell commented on src/main/scala/com/fulcrumgenomics/umi/CorrectUmis.scala
> +  @arg(doc="The number of results to cache; zero will not cache results.") val cacheSize: Int = 100000
```suggestion
  @arg(doc="The number of uncorrected UMIs to cache; zero will disable the cache.") val cacheSize: Int = 100000
```

2021-09-09 10:48 UTC, pamelarussell approved these changes
One small suggestion to clarify documentation.

2021-09-09 13:13 UTC, tfenne requested changes
I suspect this is "good enough" for what you're doing, but it's not actually an LRU cache.  To be LRU you need to update the cache on get to keep the "hot" items in cache and not have them evicted as time goes by.  I'm not sure what the overhead is though on removing and re-adding on get.  Either way, makes a good case for encapsulating the LRUCache better and not just extending Map.

2021-09-09 13:13 UTC, tfenne commented on src/main/scala/com/fulcrumgenomics/umi/CorrectUmis.scala
> +    if (cacheSize > 0 && cache.containsKey(bases)) cache.get(bases)
You're doing double work here by using `containsKey` and then `get`.  I'd rewrite to do something like 

```scala
val previous = if (cacheSize > 0) cache.get(bases) else None
previous match {
...
}
```

2021-09-09 13:13 UTC, tfenne commented on src/main/scala/com/fulcrumgenomics/umi/CorrectUmis.scala
> +}
I think:

1. This should use scala.collection.mutable.LinkedHashMap
2. It should not extend, but have the `map` as a `private` val
3. Only public methods should be `get()` and `put()`, both synchronized, with `put()` doing the eviction as needed.

2021-09-09 13:13 UTC, tfenne commented on src/main/scala/com/fulcrumgenomics/umi/CorrectUmis.scala
> +}
You could also add a `getOrElseUpdate(key: Key, value: => Value)`

2021-09-20 17:09 UTC, tfenne approved these changes

2021-09-20 22:01 UTC, merged