Command line tool to produce and print pairwise alignments.
fulcrumgenomics/fgbio pull request #739
Opened 2021-11-11 16:16 UTC by tfenne

2021-12-18 20:58 UTC, nh13 requested changes

2021-12-18 20:58 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/personal/tfenne/PairwiseAlign.scala
> + * Copyright (c) 2018 Fulcrum Genomics LLC
```suggestion
 * Copyright (c) 2021 Fulcrum Genomics LLC
```

2021-12-18 20:58 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/personal/tfenne/PairwiseAlign.scala
> +    val aligner = Aligner(1, -4, -6, -1, mode)
scoring params are hard-coded.  Nice to have them exposed on the command line.

2021-12-18 20:58 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/personal/tfenne/PairwiseAlign.scala
> +    right.paddedString().foreach(println)
Nice to have the alignment score, cigar, target start/end, query start/end printed too.  The latter are useful for local and glocal.

2021-12-21 13:06 UTC, tfenne commented
@nh13 I don't disagree with you suggestions but don't have time to act on them.  Shall we merge and can add those later if/when we want?

2026-01-21 21:19 UTC, clintval approved these changes

2026-01-21 21:19 UTC, clintval commented on src/main/scala/com/fulcrumgenomics/personal/tfenne/PairwiseAlign.scala
> +class PairwiseAlign
This is OK with me but now I'm wishing the entire `Personal` section of `fgbio --help` was secret/hidden instead of exposed. Perhaps we have a feature where if an environmental variable is set, we list out all tools including the personal tools and then we could all have that environmental variable in our personal shell configurations?

2026-05-20 01:38 UTC, closed without merging