ZipperBams to produce mate score ("ms") for samtools markdup
fulcrumgenomics/fgbio pull request #952
Opened 2023-12-18 23:59 UTC by nh13

Fixes: #951

2023-12-27 23:19 UTC, tfenne requested changes
I don't object in principal, but these should all probably be of the form:

```scala
primary.get[Int]("AS").foreach(supp("ms") = _)
```

so that it will work for aligners that don't produce an `AS` tag and on pairs where only one read is aligned.

2023-12-27 23:34 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/bam/Bams.scala
> +      second("ms") = first[Int]("AS")
```suggestion
  /** Fixes mate information and sets mate cigar and mate score on all primary and supplementary (but not secondary) records. */
  def fixMateInfo(): Unit = {
    // Developer note: the mate score ("ms") tag is used by samtools markdup
    for (primary <- r1; supp <- r2Supplementals) {
      SamPairUtil.setMateInformationOnSupplementalAlignment(supp.asSam, primary.asSam, true)
      primary.get[Int]("AS").foreach(supp("ms") = _))
    }
    for (primary <- r2; supp <- r1Supplementals) {
      SamPairUtil.setMateInformationOnSupplementalAlignment(supp.asSam, primary.asSam, true)
      primary.get[Int]("AS").foreach(supp("ms") = _))
    }
    for (first <- r1; second <- r2) {
      SamPairUtil.setMateInfo(first.asSam, second.asSam, true)
      first.get[Int]("AS").foreach(second("ms") = _))
      second.get[Int]("AS").foreach(first("ms") = _))
```

2023-12-27 23:36 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/bam/Bams.scala
> +      second.get[Int]("AS").foreach(first("ms") = _))
```suggestion
  /** Fixes mate information and sets mate cigar and mate score on all primary and supplementary (but not secondary) records. */
  def fixMateInfo(): Unit = {
    // Developer note: the mate score ("ms") tag is used by samtools markdup
    for (primary <- r1; supp <- r2Supplementals) {
      SamPairUtil.setMateInformationOnSupplementalAlignment(supp.asSam, primary.asSam, true)
      primary.get[Int]("AS").foreach(supp("ms") = _)
    }
    for (primary <- r2; supp <- r1Supplementals) {
      SamPairUtil.setMateInformationOnSupplementalAlignment(supp.asSam, primary.asSam, true)
      primary.get[Int]("AS").foreach(supp("ms") = _)
    }
    for (first <- r1; second <- r2) {
      SamPairUtil.setMateInfo(first.asSam, second.asSam, true)
      first.get[Int]("AS").foreach(second("ms") = _)
      second.get[Int]("AS").foreach(first("ms") = _)
```

2023-12-29 12:27 UTC, tfenne approved these changes
LGTM but could you add/amend a couple of tests to make sure it works on both reads that have and don't have AS set?

2024-02-02 14:57 UTC, TedBrookings approved these changes
Sorry for the delay. Looks good to me

2024-02-09 15:35 UTC, merged